import type { RouteTypesManifest } from './setup-dev-bundler'

function deterministicSerialize(obj: object): string {
  return JSON.stringify(
    obj,
    (_key, value) => {
      if (
        typeof value === 'object' &&
        value !== null &&
        !Array.isArray(value)
      ) {
        const sorted: any = {}
        Object.keys(value)
          .sort()
          .forEach((k) => {
            sorted[k] = value[k]
          })
        return sorted
      }
      return value
    },
    2
  )
}

export function generateRouteTypesFile(
  routesManifest: RouteTypesManifest
): string {
  // Only include the route data for the routes.ts file
  const cleanManifest = {
    appRoutes: routesManifest.appRoutes,
    pageRoutes: routesManifest.pageRoutes,
    layoutRoutes: routesManifest.layoutRoutes,
  }

  return `// This file is generated automatically by Next.js
// Do not edit this file manually

const routesManifest = ${deterministicSerialize(cleanManifest)} as const

type AppPageRoutes = keyof (typeof routesManifest)['appRoutes']
type PagesPageRoutes = keyof (typeof routesManifest)['pageRoutes']
type PageRoutes = AppPageRoutes | PagesPageRoutes
type LayoutRoutes = keyof (typeof routesManifest)['layoutRoutes']
type Routes = PageRoutes | LayoutRoutes

// -----------------------------------
// helpers
// -----------------------------------

type Merge<T> = { [K in keyof T]: T[K] }
// extract path params
type Grab<Path extends string> =
  Path extends \`\${string}[[...\${infer Key}]]\${infer Rest}\`
    ? Merge<{ [K in Key]: undefined | string[] } & Grab<Rest>>
  : Path extends \`\${string}[...\${infer Key}]\${infer Rest}\`
    ? Merge<{ [K in Key]: [string, ...string[]] } & Grab<Rest>>
  : Path extends \`\${string}[\${infer Key}]\${infer Rest}\`
    ? Merge<{ [K in Key]: string } & Grab<Rest>>
  : {}

type ParamMap = { [P in Routes]: Grab<P> }
export type ParamsOf<P extends Routes> = ParamMap[P]

// -----------------------------------
// layout slots
// -----------------------------------

type SlotMap = {
  [P in LayoutRoutes]:
    (typeof routesManifest)['layoutRoutes'][P] extends { slots: readonly string[] }
      ? (typeof routesManifest)['layoutRoutes'][P]['slots'][number]
      : never
}

type LayoutChildrenMap = {
  [P in LayoutRoutes]: Merge<{ children: React.ReactNode } &
    { [K in SlotMap[P]]: React.ReactNode }>
}

type LayoutChildren<P extends LayoutRoutes> = LayoutChildrenMap[P]

// -----------------------------------
// exports
// -----------------------------------

export { routesManifest }
export type { PageRoutes, LayoutRoutes }

// -----------------------------------
// global types
// -----------------------------------

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * \`\`\`tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * \`\`\`
   */
  type PageProps<P extends PageRoutes> = {
    params: Promise<ParamsOf<P>>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }
  
  /**
   * Props for Next.js App Router layout components
   * @example
   * \`\`\`tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * \`\`\`
   */
  type LayoutProps<P extends LayoutRoutes> = {
    params: Promise<ParamsOf<P>>
  } & LayoutChildren<P>
}`
}
